# Metaprogram used to generate 'test_questions.py' from 'questions.txt'

import os

def main(questions_file, index_dir, out_dir):
    
    if not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    
    with open(questions_file) as q_file, open(os.path.join(out_dir, "test_questions.py"), "w") as py_file:
        
        py_file.write("# Generated by 'meta_test_questions.py'\n\n")
        py_file.write("from utils import retriever\n")
        py_file.write("ir = retriever.Retriever(\"" + index_dir + "\")\n")
        
        q_content = q_file.read().split('\n\n')
        q_list = [q.strip() for q in q_content if q.strip()]
        
        for i, q in enumerate(q_list):
            category, question, answer = q.split('\n')
            query = "\"" + category.replace('"', '\\"') + ", " + question.replace('"', '\\"') + "\""
            answer = answer.split('|') # list of answers divided by '|' (or)
            
            py_file.write(f"\ndef test_question_{i+1}_topK():\n")
            py_file.write(f"\tresults, scores = ir.run_query({query})\n")
            py_file.write("\ttitles = [results[0, i]['title'] for i in range(results.shape[1])]\n")
            py_file.write(f"\tassert {' or '.join(f'"{ans}" in titles' for ans in answer)}\n")    

if __name__ == "__main__":
    
    import sys
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <questions_file> <index_dir> <out_dir>")
        exit(-1)
            
    # load our project wiki
    main(sys.argv[1], sys.argv[2], sys.argv[3])            
        