# Generated by 'meta_test_questions.py'

from utils import retriever
ir = retriever.Retriever(".bm25s")

def test_question_1_topK():
	results, scores = ir.run_query("NEWSPAPERS, The dominant paper in our nation's capital, it's among the top 10 U.S. papers in circulation")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Washington Post" in titles

def test_question_2_topK():
	results, scores = ir.run_query("OLD YEAR'S RESOLUTIONS, The practice of pre-authorizing presidential use of force dates to a 1955 resolution re: this island near mainland China")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Taiwan" in titles

def test_question_3_topK():
	results, scores = ir.run_query("NEWSPAPERS, Daniel Hertzberg & James B. Stewart of this paper shared a 1988 Pulitzer for their stories about insider trading")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Wall Street Journal" in titles

def test_question_4_topK():
	results, scores = ir.run_query("BROADWAY LYRICS, Song that says, \"you make me smile with my heart; your looks are laughable, unphotographable\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "My Funny Valentine" in titles

def test_question_5_topK():
	results, scores = ir.run_query("POTPOURRI, In 2011 bell ringers for this charity started accepting digital donations to its red kettle")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Salvation Army" in titles or "Salvation Army" in titles

def test_question_6_topK():
	results, scores = ir.run_query("STATE OF THE ART MUSEUM (Alex: We'll give you the museum. You give us the state.), The Naples Museum of Art")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Florida" in titles

def test_question_7_topK():
	results, scores = ir.run_query("\"TIN\" MEN, This Italian painter depicted the \"Adoration of the Golden Calf\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Tintoretto" in titles

def test_question_8_topK():
	results, scores = ir.run_query("UCLA CELEBRITY ALUMNI, This woman who won consecutive heptathlons at the Olympics went to UCLA on a basketball scholarship")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Jackie Joyner-Kersee" in titles

def test_question_9_topK():
	results, scores = ir.run_query("SERVICE ORGANIZATIONS, Originally this club's emblem was a wagon wheel; now it's a gearwheel with 24 cogs & 6 spokes")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Rotary International" in titles

def test_question_10_topK():
	results, scores = ir.run_query("AFRICAN CITIES, Several bridges, including El Tahrir, cross the Nile in this capital")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Cairo" in titles

def test_question_11_topK():
	results, scores = ir.run_query("HISTORICAL QUOTES, After the fall of France in 1940, this general told his country, \"France has lost a battle. But France has not lost the war\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Charles de Gaulle" in titles or "de Gaulle" in titles

def test_question_12_topK():
	results, scores = ir.run_query("STATE OF THE ART MUSEUM (Alex: We'll give you the museum. You give us the state.), The Taft Museum of Art")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Ohio" in titles

def test_question_13_topK():
	results, scores = ir.run_query("CEMETERIES, The mast from the USS Maine is part of the memorial to the ship & crew at this national cemetery")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Arlington National Cemetery" in titles or "Arlington Cemetery" in titles

def test_question_14_topK():
	results, scores = ir.run_query("GOLDEN GLOBE WINNERS, In 2009: Joker on film")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Heath Ledger" in titles

def test_question_15_topK():
	results, scores = ir.run_query("HISTORICAL HODGEPODGE, It was the peninsula fought over in the peninsular war of 1808 to 1814")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Iberia" in titles or "Iberian Peninsula" in titles

def test_question_16_topK():
	results, scores = ir.run_query("CONSERVATION, In 1980 China founded a center for these cute creatures in its bamboo-rich Wolong Nature Preserve")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Panda" in titles or "Giant panda" in titles

def test_question_17_topK():
	results, scores = ir.run_query("'80s NO.1 HITMAKERS, 1988: \"Father Figure\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "George Michael" in titles

def test_question_18_topK():
	results, scores = ir.run_query("AFRICAN-AMERICAN WOMEN, In an essay defending this 2011 film, Myrlie Evers-Williams said, \"My mother was\" this film \"& so was her mother\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Help" in titles

def test_question_19_topK():
	results, scores = ir.run_query("SERVICE ORGANIZATIONS, Father Michael McGivney founded this fraternal society for Catholic laymen in 1882")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Knights of Columbus" in titles

def test_question_20_topK():
	results, scores = ir.run_query("CONSERVATION, Early projects of the WWF, this organization, included work with the bald eagle & the red wolf")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "World Wide Fund" in titles or "World Wide Fund for Nature" in titles

def test_question_21_topK():
	results, scores = ir.run_query("CONSERVATION, Indonesia's largest lizard, it's protected from poachers, though we wish it could breathe fire to do the job itself")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Komodo dragon" in titles

def test_question_22_topK():
	results, scores = ir.run_query("1920s NEWS FLASH!, Nov. 28, 1929! This man & his chief pilot Bernt Balchen fly to South Pole! Yowza! You'll be an admirable admiral, sir!")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Richard Byrd" in titles or "Richard E. Byrd" in titles

def test_question_23_topK():
	results, scores = ir.run_query("CEMETERIES, On May 5, 1878 Alice Chambers was the last person buried in this Dodge City, Kansas cemetery")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Boot Hill" in titles

def test_question_24_topK():
	results, scores = ir.run_query("CAMBODIAN HISTORY & CULTURE, The Royal Palace grounds feature a statue of King Norodom, who in the late 1800s was compelled to first put his country under the control of this European power; of course, it was sculpted in that country")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "France" in titles

def test_question_25_topK():
	results, scores = ir.run_query("HISTORICAL HODGEPODGE, In the 400s B.C. this Chinese philosopher went into exile for 12 years")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Confucius" in titles

def test_question_26_topK():
	results, scores = ir.run_query("AFRICAN-AMERICAN WOMEN, Bessie Coleman, the first black woman licensed as a pilot, landed a street named in her honor at this Chicago airport")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "O'Hare" in titles or "O'Hare International Airport" in titles

def test_question_27_topK():
	results, scores = ir.run_query("HISTORICAL HODGEPODGE, The Ammonites held sway in this Mideast country in the 1200s B.C. & the capital is named for them")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Jordan" in titles

def test_question_28_topK():
	results, scores = ir.run_query("HE PLAYED A GUY NAMED JACK RYAN IN..., \"The Sum of All Fears\"; he also won a screenwriting Oscar for \"Good Will Hunting\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Ben Affleck" in titles

def test_question_29_topK():
	results, scores = ir.run_query("POTPOURRI, One of the N.Y. Times' headlines on this landmark 1973 Supreme Court decision was \"Cardinals shocked\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Roe v. Wade" in titles

def test_question_30_topK():
	results, scores = ir.run_query("I'M BURNIN' FOR YOU, France's Philip IV--known as \"The Fair\"--had Jacques De Molay, the last Grand Master of this order, burned in 1314")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Knights Templar" in titles

def test_question_31_topK():
	results, scores = ir.run_query("STATE OF THE ART MUSEUM (Alex: We'll give you the museum. You give us the state.), The Georgia O'Keeffe Museum")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "New Mexico" in titles

def test_question_32_topK():
	results, scores = ir.run_query("AFRICAN CITIES, The name of this largest Moroccan city combines 2 Spanish words")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Casablanca" in titles

def test_question_33_topK():
	results, scores = ir.run_query("NAME THE PARENT COMPANY, Jell-O")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Kraft Foods" in titles

def test_question_34_topK():
	results, scores = ir.run_query("GOLDEN GLOBE WINNERS, 2011: Chicago mayor Tom Kane")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Kelsey Grammer" in titles

def test_question_35_topK():
	results, scores = ir.run_query("THE RESIDENTS, Title residence of Otter, Flounder, Pinto & Bluto in a 1978 comedy")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Animal House" in titles

def test_question_36_topK():
	results, scores = ir.run_query("UCLA CELEBRITY ALUMNI, Neurobiologist Amy Farrah Fowler on \"The Big Bang Theory\", in real life she has a Ph.D. in neuroscience from UCLA")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Mayim Bialik" in titles

def test_question_37_topK():
	results, scores = ir.run_query("NOTES FROM THE CAMPAIGN TRAIL, In \"The Deadlocked Election of 1800\", James R. Sharp outlines the fall of this dueling vice president")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Aaron Burr" in titles

def test_question_38_topK():
	results, scores = ir.run_query("\"TIN\" MEN, He served in the KGB before becoming president & then prime minister of Russia")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Vladimir Putin" in titles or "Putin" in titles

def test_question_39_topK():
	results, scores = ir.run_query("AFRICAN-AMERICAN WOMEN, When asked to describe herself, she says first & foremost, she is Malia & Sasha's mom")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Michelle Obama" in titles

def test_question_40_topK():
	results, scores = ir.run_query("POETS & POETRY, She wrote, \"My candle burns at both ends... but, ah, my foes, and oh, my friends--it gives a lovely light\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Edna St. Vincent Millay" in titles

def test_question_41_topK():
	results, scores = ir.run_query("CAPITAL CITY CHURCHES (Alex: We'll give you the church. You tell us the capital city in which it is located.), In this Finnish city, the Lutheran Cathedral, also known as Tuomiokirkko")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Helsinki" in titles

def test_question_42_topK():
	results, scores = ir.run_query("NAME THE PARENT COMPANY, Milton Bradley games")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Hasbro" in titles

def test_question_43_topK():
	results, scores = ir.run_query("OLD YEAR'S RESOLUTIONS, The Kentucky & Virginia resolutions were passed to protest these controversial 1798 acts of Congress")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Alien and Sedition Acts" in titles

def test_question_44_topK():
	results, scores = ir.run_query("'80s NO.1 HITMAKERS, 1983: \"Beat It\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Michael Jackson" in titles

def test_question_45_topK():
	results, scores = ir.run_query("GOLDEN GLOBE WINNERS, In 2009: Sookie Stackhouse")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Anna Paquin" in titles

def test_question_46_topK():
	results, scores = ir.run_query("HISTORICAL HODGEPODGE, This member of the Nixon & Ford cabinets was born in Furth, Germany in 1923")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Henry Kissinger" in titles

def test_question_47_topK():
	results, scores = ir.run_query("CAPITAL CITY CHURCHES (Alex: We'll give you the church. You tell us the capital city in which it is located.), The High Kirk of St. Giles, where John Knox was minister")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Edinburgh" in titles

def test_question_48_topK():
	results, scores = ir.run_query("UCLA CELEBRITY ALUMNI, For the brief time he attended, he was a rebel with a cause, even landing a lead role in a 1950 stage production")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "James Dean" in titles

def test_question_49_topK():
	results, scores = ir.run_query("NAME THE PARENT COMPANY, Fisher-Price toys")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Mattel" in titles

def test_question_50_topK():
	results, scores = ir.run_query("HISTORICAL QUOTES, In a 1959 American kitchen exhibit in Moscow, he told Khrushchev, \"In America, we like to make life easier for women\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Richard Nixon" in titles or "Nixon" in titles

def test_question_51_topK():
	results, scores = ir.run_query("POETS & POETRY, One of his \"Tales of a Wayside Inn\" begins, \"Listen, my children, and you shall hear of the midnight ride of Paul Revere\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Henry Wadsworth Longfellow" in titles

def test_question_52_topK():
	results, scores = ir.run_query("NOTES FROM THE CAMPAIGN TRAIL, This bestseller about problems on the McCain-Palin ticket became an HBO movie with Julianne Moore")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Game Change" in titles

def test_question_53_topK():
	results, scores = ir.run_query("THAT 20-AUGHTS SHOW, A 2-part episode of \"JAG\" introduced this Mark Harmon drama")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "NCIS" in titles

def test_question_54_topK():
	results, scores = ir.run_query("AFRICAN CITIES, This port is the southernmost of South Africa's 3 capitals")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Cape Town" in titles

def test_question_55_topK():
	results, scores = ir.run_query("THE QUOTABLE KEATS, Keats was quoting this Edmund Spenser poem when he told Shelley to \"'load every rift' of your subject with ore\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Faerie Queene" in titles

def test_question_56_topK():
	results, scores = ir.run_query("THE QUOTABLE KEATS, In an 1819 letter Keats wrote that this lord & poet \"cuts a figure, but he is not figurative\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Lord Byron" in titles

def test_question_57_topK():
	results, scores = ir.run_query("GREEK FOOD & DRINK, This clear Greek liqueur is quite potent, so it's usually mixed with water, which turns it white & cloudy")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Ouzo" in titles

def test_question_58_topK():
	results, scores = ir.run_query("OLD YEAR'S RESOLUTIONS, Feb. 1, National Freedom Day, is the date in 1865 when a resolution sent the states an amendment ending this")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Slavery" in titles or "Slavery in the United States" in titles

def test_question_59_topK():
	results, scores = ir.run_query("RANKS & TITLES, This person is the queen's representative in Canada; currently the office is held by David Johnston")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Governor General of Canada" in titles

def test_question_60_topK():
	results, scores = ir.run_query("\"TIN\" MEN, He earned the \"fifth Beatle\" nickname by producing all of the Beatles' albums")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "George Martin" in titles

def test_question_61_topK():
	results, scores = ir.run_query("NEWSPAPERS, Early in their careers, Mark Twain & Bret Harte wrote pieces for this California city's Chronicle")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "San Francisco" in titles

def test_question_62_topK():
	results, scores = ir.run_query("POTPOURRI, Large specimens of this marsupial can leap over barriers 6 feet high")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Kangaroo" in titles

def test_question_63_topK():
	results, scores = ir.run_query("GREEK FOOD & DRINK, Because it's cured & stored in brine, this crumbly white cheese made from sheep's milk is often referred to as pickled cheese")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Feta" in titles

def test_question_64_topK():
	results, scores = ir.run_query("1920s NEWS FLASH!, 1927! Gene Tunney takes a long count in the squared circle but rises to defeat this \"Manassa Mauler\"! Howzabout that!")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Jack Dempsey" in titles

def test_question_65_topK():
	results, scores = ir.run_query("RANKS & TITLES, Italian for \"leader\", it was especially applied to Benito Mussolini")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Duce" in titles

def test_question_66_topK():
	results, scores = ir.run_query("STATE OF THE ART MUSEUM (Alex: We'll give you the museum. You give us the state.), The Kalamazoo Institute of Arts")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Michigan" in titles

def test_question_67_topK():
	results, scores = ir.run_query("STATE OF THE ART MUSEUM (Alex: We'll give you the museum. You give us the state.), The Sun Valley Center for the Arts")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Idaho" in titles

def test_question_68_topK():
	results, scores = ir.run_query("\"TIN\" MEN, You can't mention this shortstop without mentioning his double-play associates Evers & Chance")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Joe Tinker" in titles

def test_question_69_topK():
	results, scores = ir.run_query("NEWSPAPERS, In 1840 Horace Greeley began publishing \"The Log Cabin\", a weekly campaign paper in support of this Whig candidate")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "William Henry Harrison" in titles

def test_question_70_topK():
	results, scores = ir.run_query("I'M BURNIN' FOR YOU, Pierre Cauchon, Bishop of Beauvais, presided over the trial of this woman who went up in smoke May 30, 1431")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Joan of Arc" in titles or "Jeanne d'Arc" in titles

def test_question_71_topK():
	results, scores = ir.run_query("COMPLETE DOM-INATION(Alex: Not \"domination.\"), This Wisconsin city claims to have built the USA's only granite dome")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Madison" in titles

def test_question_72_topK():
	results, scores = ir.run_query("NEWSPAPERS, This Georgia paper is known as the AJC for short")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Atlanta Journal-Constitution" in titles

def test_question_73_topK():
	results, scores = ir.run_query("AFRICAN CITIES, Wooden 2-story verandas in this Liberian capital are an architectural link to the U.S. south")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Monrovia" in titles

def test_question_74_topK():
	results, scores = ir.run_query("COMPLETE DOM-INATION(Alex: Not \"domination.\"), This New Orleans venue reopened Sept. 25, 2006")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Mercedes-Benz Superdome" in titles or "The Superdome" in titles

def test_question_75_topK():
	results, scores = ir.run_query("HE PLAYED A GUY NAMED JACK RYAN IN..., \"The Hunt for Red October\"; he went more comedic as Jack Donaghy on \"30 Rock\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Alec Baldwin" in titles

def test_question_76_topK():
	results, scores = ir.run_query("AFRICAN-AMERICAN WOMEN, Rita Dove titled a collection of poems \"On the Bus with\" this woman")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Rosa Parks" in titles

def test_question_77_topK():
	results, scores = ir.run_query("HE PLAYED A GUY NAMED JACK RYAN IN..., \"Patriot Games\"; he's had other iconic roles, in space & underground")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Harrison Ford" in titles

def test_question_78_topK():
	results, scores = ir.run_query("COMPLETE DOM-INATION(Alex: Not \"domination.\"), This sacred structure dates from the late 600's A.D.")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Dome of the Rock" in titles

def test_question_79_topK():
	results, scores = ir.run_query("'80s NO.1 HITMAKERS, 1988: \"Man In The Mirror\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Michael Jackson" in titles

def test_question_80_topK():
	results, scores = ir.run_query("CAPITAL CITY CHURCHES (Alex: We'll give you the church. You tell us the capital city in which it is located.), Matthias Church, or Matyas Templom, where Franz Joseph was crowned in 1867")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Budapest" in titles

def test_question_81_topK():
	results, scores = ir.run_query("UCLA CELEBRITY ALUMNI, Attending UCLA in the '60s, he was no \"Meathead\", he just played one later on television")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Rob Reiner" in titles

def test_question_82_topK():
	results, scores = ir.run_query("THE RESIDENTS, Kinch, Carter & LeBeau were all residents of Stalag 13 on this TV show")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Hogan's Heroes" in titles

def test_question_83_topK():
	results, scores = ir.run_query("1920s NEWS FLASH!, News flash! This less-than-yappy pappy is sixth veep to be nation's top dog after chief takes deep sleep!")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Calvin Coolidge" in titles

def test_question_84_topK():
	results, scores = ir.run_query("GOLDEN GLOBE WINNERS, In 2001: The president of the United States on television")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Martin Sheen" in titles

def test_question_85_topK():
	results, scores = ir.run_query("'80s NO.1 HITMAKERS, 1989: \"Miss You Much\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Janet Jackson" in titles

def test_question_86_topK():
	results, scores = ir.run_query("1920s NEWS FLASH!, 1922: It's the end of an empire! This empire, in fact! After 600 years, it's goodbye, this, hello, Turkish Republic!")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Ottoman Empire" in titles

def test_question_87_topK():
	results, scores = ir.run_query("NAME THE PARENT COMPANY, Crest toothpaste")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Procter & Gamble" in titles

def test_question_88_topK():
	results, scores = ir.run_query("HISTORICAL QUOTES, In 1888 this Chancellor told the Reichstag, \"we Germans fear God, but nothing else in the world\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Otto von Bismarck" in titles or "Von Bismarck" in titles

def test_question_89_topK():
	results, scores = ir.run_query("POETS & POETRY, In 1787 he signed his first published poem \"Axiologus\"; axio- is from the Greek for \"worth\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "William Wordsworth" in titles

def test_question_90_topK():
	results, scores = ir.run_query("CAMBODIAN HISTORY & CULTURE, Not to be confused with karma, krama is a popular accessory sold in cambodia; the word means \"scarf\" in this national language of Cambodia")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Khmer language" in titles

def test_question_91_topK():
	results, scores = ir.run_query("CAMBODIAN HISTORY & CULTURE, Phnom Penh's notorious gridlock is circumvented by the nimble tuk-tuk, a motorized taxi that's also known as an auto this, a similar Asian conveyance.")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Rickshaw" in titles

def test_question_92_topK():
	results, scores = ir.run_query("'80s NO.1 HITMAKERS, 1980: \"Rock With You\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Michael Jackson" in titles

def test_question_93_topK():
	results, scores = ir.run_query("NOTES FROM THE CAMPAIGN TRAIL, The Pulitzer-winning \"The Making of the President 1960\" covered this man's successful presidential campaign")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "JFK" in titles or "John F. Kennedy" in titles

def test_question_94_topK():
	results, scores = ir.run_query("SERVICE ORGANIZATIONS, In 1843 Isaac Dittenhoefer became the first pres. of this Jewish club whose name means \"children of the covenant\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "B'nai B'rith" in titles

def test_question_95_topK():
	results, scores = ir.run_query("THE RESIDENTS, Don Knotts took over from Norman Fell as the resident landlord on this sitcom")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Three's Company" in titles

def test_question_96_topK():
	results, scores = ir.run_query("OLD YEAR'S RESOLUTIONS, U.N. Res. 242 supports \"secure and recognized boundaries\" for Israel & neighbors following this June 1967 war")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "The Six Day War" in titles

def test_question_97_topK():
	results, scores = ir.run_query("UCLA CELEBRITY ALUMNI, This blonde beauty who reprised her role as Amanda on the new \"Melrose Place\" was a psychology major")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Heather Locklear" in titles

def test_question_98_topK():
	results, scores = ir.run_query("GREEK FOOD & DRINK, The name of this dish of marinated lamb, skewered & grilled, comes from the Greek for \"skewer\" & also starts with \"s\"")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Souvlaki" in titles

def test_question_99_topK():
	results, scores = ir.run_query("NAME THE PARENT COMPANY, Post-it notes")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "3M" in titles

def test_question_100_topK():
	results, scores = ir.run_query("GOLDEN GLOBE WINNERS, In 2010: As Sherlock Holmes on film")
	titles = [results[0, i]['title'] for i in range(results.shape[1])]
	assert "Robert Downey, Jr." in titles
